apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nginx
  namespace: argocd
spec: 
  project: default
  source: 
    repoURL: https://github.com/Tostaza/gitops-workshop.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy: 
    syncOptions: 
    - CreateNamespace=true